name: NexusCore
version: '${project.version}'
main: cc.synkdev.nexusCore.bukkit.NexusCore
api-version: '1.13'
authors: [ Synk ]
folia-supported: true
permissions:
  nexuscore.report:
    description: Send information dumps about your server
    default: op
  nexuscore.command.reload:
    description: Reload the plugin
    default: op
  nexuscore.command.support:
    description: Use the remote support feature
    default: op
softdepend:
  - RemoteSupportNexus
